apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sympathetic-emu-python 
  janus-idp.io/tekton: sympathetic-emu-python
  backstage.io/kubernetes-id: sympathetic-emu-python
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: sympathetic-emu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  